[package]
name = "quark-gui-win32"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Quark Downloader Win32 frontend"
publish = false

[lib]
name = "quark_gui_win32"
path = "src/lib.rs"

[[bin]]
name = "quark-downloader-gui-win32"
path = "src/bin.rs"

[dependencies]
quark-core = { path = "../quark-core" }
quark-gui = { path = "../quark-gui" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_DataExchange",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_UI_Controls",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_WindowsAndMessaging",
] }
